apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: kube-02
  ports: 
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kube-02
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: kube-02
  template:
    metadata: 
      labels:
        app: kube-02
    spec:
      containers: 
        - name: kube-02
          image: edalonzoh/kub-01
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
