apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template: 
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: edalonzoh/kube-demo-tasks:latest
          env: 
            - name: AUTH_ADDRESS
              value: "auth-service.default"
              # value: 10.108.120.198
            - name: TASKS_FOLDER
              value: tasks