apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: edalonzoh/kube-demo-users:latest
          env: 
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: edalonzoh/kube-demo-auth:latest

---
apiVersion: v1
kind: Service
metadata: 
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
