apiVersion: v1
kind: Service
metadata: 
  name: service-kube-02
spec:
  selector:
    app: story
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kube-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template: 
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: container-kube-02
          image: edalonzoh/kube-02:3
          volumeMounts: 
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
          #hostPath:  
          #  path: /data
          #  type: DirectoryOrCreate
          #emptyDir: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 1Gi